### ISSUE TITLE
Feedback on metadata and kind

### ISSUE THREAD

**Issue by ralekseenkov** [Aptomi/aptomi#147]
Got this as a user feedback (from Alex).

YAML is much more readable when Kind is placed first, outside of Metadata. So that you start defining an object in the first row instead of hiding object kind inside metadata.

I.e. this:

```
kind: cluster
metadata:
  name: mycluster
  namespace: main
```

vs.

```
metadata:
  kind: cluster
  name: mycluster
  namespace: main
```

Thoughts?
