### ISSUE TITLE
Spark from twitter-stats example has an issue running on the latest k8s (GKE, Azure)

### ISSUE THREAD

**Issue by ralekseenkov** [Aptomi/aptomi#323]
Fails to start:
```
chmod: changing permissions of '/usr/local/spark/conf/spark-env.sh': Read-only file system
```

Likely related to:
```
volumes:
      - configMap:
          defaultMode: 420
          name: spark-conf-a-f5mbvioa3a3ac
        name: spark-con
```
